package com.movie.mash.up.client;

import java.util.*;

//Logging facility
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class WordMap
{
    
    private Hashtable<String, Boolean> stoplist;
    private Hashtable<String, Boolean> negativelist;
    private Hashtable<String, Boolean> positivelist;
    
    
    /*******************************/
    public static final String POSITIVE_HAPPY="happy";
	public static final String POSITIVE_GRATEFUL="grateful";
	public static final String POSITIVE_DETERMINED="determined";
	public static final String POSITIVE_PROFESSIONAL="professional";
	public static final String POSITIVE_SWELL="swell";
	public static final String POSITIVE_AUTHENTIC="authentic";
	public static final String POSITIVE_CONTENT="content";
	public static final String POSITIVE_FOCUSED="focused";
	public static final String POSITIVE_EXTRAORDINARY="extraordinary";
	public static final String POSITIVE_DELIGHTFUL="delightful";
	public static final String POSITIVE_IMAGINATIVE="imaginative";
	public static final String POSITIVE_SUCCESSFUL="successful";
	public static final String POSITIVE_HEROIC="heroic";
	public static final String POSITIVE_CHEERFUL="cheerful";
	public static final String POSITIVE_UNIQUE="unique";
	public static final String POSITIVE_TOUGH="tough";
	public static final String POSITIVE_GLAD="glad";
	public static final String POSITIVE_DESIRABLE="desirable";
	public static final String POSITIVE_VALIANT="valiant";
	public static final String POSITIVE_WORTHY="worthy";
	public static final String POSITIVE_COLORFUL="colorful";
	public static final String POSITIVE_JOYFUL="joyful";
	public static final String POSITIVE_LAUDABLE="laudable";
	public static final String POSITIVE_CUTE="cute";
	public static final String POSITIVE_DEPENDABLE="dependable";
	public static final String POSITIVE_REMARKABLE="remarkable";
	public static final String POSITIVE_CONFIDENT="confident";
	public static final String POSITIVE_FUNNY="funny";
	public static final String POSITIVE_MAGNETIC="magnetic";
	public static final String POSITIVE_ECSTATIC="ecstatic";
	public static final String POSITIVE_LOVELY="lovely";
	public static final String POSITIVE_ENTERTAINING="entertaining";
	public static final String POSITIVE_DECENT="decent";
	public static final String POSITIVE_HELPFUL="helpful";
	public static final String POSITIVE_CONVINCING="convincing";
	public static final String POSITIVE_BEAUTIFUL="beautiful";
	public static final String POSITIVE_COMMENDABLE="commendable";
	public static final String POSITIVE_SENSUAL="sensual";
	public static final String POSITIVE_SUBLIME="sublime";
	public static final String POSITIVE_ENGAGING="engaging";
	public static final String POSITIVE_HUMOROUS="humorous";
	public static final String POSITIVE_WARM="warm";
	public static final String POSITIVE_PLEASANT="pleasant";
	public static final String POSITIVE_ORIGINAL="original";
	public static final String POSITIVE_SUPERB="superb";
	public static final String POSITIVE_INTELLIGENT="intelligent";
	public static final String POSITIVE_PLAYFUL="playful";
	public static final String POSITIVE_IMPRESSIVE="impressive";
	public static final String POSITIVE_ELATED="elated";
	public static final String POSITIVE_CREDIBLE="credible";
	public static final String POSITIVE_WONDERFUL="wonderful";
	public static final String POSITIVE_BRIGHT="bright";
	public static final String POSITIVE_FANTASTIC="fantastic";
	public static final String POSITIVE_RICH="rich";
	public static final String POSITIVE_BOLD="bold";
	public static final String POSITIVE_FUN="fun";
	public static final String POSITIVE_NICE="nice";
	public static final String POSITIVE_CREATIVE="creative";
	public static final String POSITIVE_SATISFIED="satisfied";
	public static final String POSITIVE_PRECIOUS="precious";
	public static final String POSITIVE_GREGARIOUS="gregarious";
	public static final String POSITIVE_INNOCENT="innocent";
	public static final String POSITIVE_PERFECT="perfect";
	public static final String POSITIVE_INDUSTRIOUS="industrious";
	public static final String POSITIVE_PRACTICAL="practical";
	public static final String POSITIVE_STABLE="stable";
	public static final String POSITIVE_LOYAL="loyal";
	public static final String POSITIVE_CASUAL="casual";
	public static final String POSITIVE_COMFORTABLE="comfortable";
	public static final String POSITIVE_SENSIBLE="sensible";
	public static final String POSITIVE_RELAXED="relaxed";
	public static final String POSITIVE_MERRY="merry";
	public static final String POSITIVE_BRILLIANT="brilliant";
	public static final String POSITIVE_FASCINATING="fascinating";
	public static final String POSITIVE_APPRECIATIVE="appreciative";
	public static final String POSITIVE_SOULFUL="soulful";
	public static final String POSITIVE_CORDIAL="cordial";
	public static final String POSITIVE_SPARKLING="sparkling";
	public static final String POSITIVE_GLEEFUL="gleeful";
	public static final String POSITIVE_RADIANT="radiant";
	public static final String POSITIVE_RESOLUTE="resolute";
	public static final String POSITIVE_BLISSFUL="blissful";
	public static final String POSITIVE_GENUINE="genuine";
	public static final String POSITIVE_ARTISTIC="artistic";
	public static final String POSITIVE_ADMIRABLE="admirable";
	public static final String POSITIVE_REAL="real";
	public static final String POSITIVE_POLISHED="polished";
	public static final String POSITIVE_DESERVING="deserving";
	public static final String POSITIVE_DARING="daring";
	public static final String POSITIVE_FREE="free";
	public static final String POSITIVE_GREAT="great";
	public static final String POSITIVE_ELEGANT="elegant";
	public static final String POSITIVE_CHIC="chic";
	public static final String POSITIVE_SLEEK="sleek";
	public static final String POSITIVE_EXCELLENT="excellent";
	public static final String POSITIVE_AFFABLE="affable";
	public static final String POSITIVE_HOPEFUL="hopeful";
	public static final String POSITIVE_STYLISH="stylish";
	public static final String POSITIVE_SUBTLE="subtle";
	public static final String POSITIVE_PEACEFUL="peaceful";
	public static final String POSITIVE_BRAINY="brainy";
	public static final String POSITIVE_DECISIVE="decisive";
	
	public static final String POSITIVE_GOOD="good";
	public static final String POSITIVE_CALM="calm";
	public static final String POSITIVE_AMAZING="amazing";
	public static final String POSITIVE_WISE="wise";
	public static final String POSITIVE_FABULOUS="fabulous";
	public static final String POSITIVE_POWERFUL="powerful";
	public static final String POSITIVE_SPECIAL="special";
	public static final String POSITIVE_STRONG="strong";
	public static final String POSITIVE_CAPTIVATING="captivating";
	public static final String POSITIVE_PASSIONATE="passionate";
	public static final String POSITIVE_ENTHUSIASTIC="enthusiastic";
	public static final String POSITIVE_BALANCED="balanced";
	public static final String POSITIVE_THRIFTY="thrifty";
	public static final String POSITIVE_AMIABLE="amiable";
	public static final String POSITIVE_VERSATILE="versatile";
	public static final String POSITIVE_HEAVENLY="heavenly";
	public static final String POSITIVE_LIVELY="lively";
	public static final String POSITIVE_ATTRACTIVE="attractive";
	public static final String POSITIVE_POETIC="poetic";
	public static final String POSITIVE_SENTIMENTAL="sentimental";
	public static final String POSITIVE_ADORABLE="adorable";
	public static final String POSITIVE_LIKEABLE="likeable";
	public static final String POSITIVE_ROMANTIC="romantic";
	public static final String POSITIVE_REFINED="refined";
	public static final String POSITIVE_POSITIVE="positive";
	
	public static final String POSITIVE_RESPECTFUL="respectful";
	public static final String POSITIVE_HILARIOUS="hilarious";
	public static final String POSITIVE_PRICELESS="priceless";
	public static final String POSITIVE_REASONABLE="reasonable";
	public static final String POSITIVE_FASHIONABLE="fashionable";
	public static final String POSITIVE_FORTHRIGHT="forthright";
	public static final String POSITIVE_COMELY="comely";
	public static final String POSITIVE_SPIRITUAL="spiritual";
	public static final String POSITIVE_LIGHT="light";
	public static final String POSITIVE_MATURE="mature";
	public static final String POSITIVE_CANDID="candid";
	public static final String POSITIVE_ENERGETIC="energetic";
	public static final String POSITIVE_SOPHISTICATED="sophisticated";
	public static final String POSITIVE_SPLENDID="splendid";
	public static final String POSITIVE_SUNNY="sunny";
	public static final String POSITIVE_ROSY="rosy";
	public static final String POSITIVE_MODERN="modern";
	public static final String POSITIVE_AWESOME="awesome";
	public static final String POSITIVE_SWEET="sweet";
	public static final String POSITIVE_TERRIFIC="terrific";
 
    
	
	
    
		public static final String NEGATIVE_EVIL="evil";
		public static final String NEGATIVE_EMBARASSED="embarrassed";
		public static final String NEGATIVE_DRACONIAN="draconian";
		public static final String NEGATIVE_DISTURBING="disturbing";
		public static final String NEGATIVE_DEPRESSED="depressed";
		public static final String NEGATIVE_DISAGREEABLE="disagreeable";
		public static final String NEGATIVE_DEFECTIVE="defective";
		public static final String NEGATIVE_DEFEATED="defeated";
		public static final String NEGATIVE_DECEITFUL="deceitful";
		public static final String NEGATIVE_DANGEROUS="dangerous";
		public static final String NEGATIVE_CRUEL="cruel";
		public static final String NEGATIVE_CREEPY="creepy";
		public static final String NEGATIVE_CYNICAL="cynical";
		public static final String NEGATIVE_CRAZY="crazy";
		public static final String NEGATIVE_COWARDLY="cowardly";
		public static final String NEGATIVE_CONFUSED="confused";
		public static final String NEGATIVE_CLUMSY="clumsy";
		public static final String NEGATIVE_CARELESS="careless";
		public static final String NEGATIVE_CALLOUS="callous";
		public static final String NEGATIVE_BORING="boring";
		public static final String NEGATIVE_ANGRY="angry";
		public static final String NEGATIVE_ANNOYED="annoyed";
		public static final String NEGATIVE_ARROGANT="arrogant";
		public static final String NEGATIVE_ASHAMED="ashamed";
		public static final String NEGATIVE_AWFUL="awful";
		public static final String NEGATIVE_BAD="bad";
		public static final String NEGATIVE_AMBIGUOUS="ambiguous";
		public static final String NEGATIVE_BEWILDERED="bewildered";
		public static final String NEGATIVE_AFRAID="afraid";
		public static final String NEGATIVE_ALOOF="aloof";
		public static final String NEGATIVE_ABUSIVE="abusive";
		public static final String NEGATIVE_ABRUPT="abrupt";
		public static final String NEGATIVE_FANATICAL="fanatical";
		public static final String NEGATIVE_PANICKY="panicky";
		public static final String NEGATIVE_OBNOXIOUS="obnoxious";
		public static final String NEGATIVE_MALICIOUS="malicious";
		public static final String NEGATIVE_MATERIALISTIC="materialistic";
		public static final String NEGATIVE_PATHETIC="pathetic";
		public static final String NEGATIVE_LACKING="lacking";
		public static final String NEGATIVE_JITTERY="jittery";
		public static final String NEGATIVE_MEAN="mean";
		public static final String NEGATIVE_OUTRAGEOUS="outrageous";
		public static final String NEGATIVE_HORRIBLE="horrible";
		public static final String NEGATIVE_HESITANT="hesitant";
		public static final String NEGATIVE_HELPLESS="helpless";
		public static final String NEGATIVE_FRIGHTENED="frightened";
		public static final String NEGATIVE_FRETFUL="fretful";
		public static final String NEGATIVE_FRANTIC="frantic";
		public static final String NEGATIVE_FORGETFUL="forgetful";
		public static final String NEGATIVE_FOOLISH="foolish";
		public static final String NEGATIVE_FLIPPANT="flippant";
		public static final String NEGATIVE_FLASHY="flashy";
		public static final String NEGATIVE_FILTHY="filthy";
		public static final String NEGATIVE_FIERCE="fierce";
		public static final String NEGATIVE_NOISY="noisy";
		public static final String NEGATIVE_LONELY="lonely";
		public static final String NEGATIVE_NAIVE="naive";
		public static final String NEGATIVE_NASTY="nasty";
		public static final String NEGATIVE_NERVOUS="nervous";
		public static final String NEGATIVE_LAZY="lazy";
		public static final String NEGATIVE_REPULSIVE="repulsive";
		public static final String NEGATIVE_GRUMPY="grumpy";
		public static final String NEGATIVE_QUARRELSOME="quarrelsome";
		public static final String NEGATIVE_IGNORANT="ignorant";
		public static final String NEGATIVE_FURTIVE="furtive";
		public static final String NEGATIVE_GULLIBLE="gullible";
		public static final String NEGATIVE_HURT="hurt";
		public static final String NEGATIVE_POSSESSIVE="possessive";
		public static final String NEGATIVE_ILL="ill";
		public static final String NEGATIVE_IRRESOLUTE="irresolute";
		public static final String NEGATIVE_JEALOUS="jealous";
		public static final String NEGATIVE_RUTHLESS="ruthless";
		public static final String NEGATIVE_SAD="sad";
		public static final String NEGATIVE_SCARY="scary";
		public static final String NEGATIVE_SECRETIVE="secretive";
		public static final String NEGATIVE_SELFISH="selfish";
		public static final String NEGATIVE_SILLY="silly";
		public static final String NEGATIVE_SLOW="slow";
		public static final String NEGATIVE_SNEAKY="sneaky";
		public static final String NEGATIVE_SNOBBISH="snobbish";
		public static final String NEGATIVE_STRANGE="strange";
		public static final String NEGATIVE_SULKY="sulky";
		public static final String NEGATIVE_TERRIBLE="terrible";
		public static final String NEGATIVE_THREATENING="threatening";
		public static final String NEGATIVE_TIGHT="tight";
		public static final String NEGATIVE_TIMID="timid";
		public static final String NEGATIVE_TIRED="tired";
		public static final String NEGATIVE_TIRESOME="tiresome";
		public static final String NEGATIVE_TROUBLED="troubled";
		public static final String NEGATIVE_UPSET="upset";
		public static final String NEGATIVE_UNSURE="unsure";
		public static final String NEGATIVE_UNSUITABLE="unsuitable";
		public static final String NEGATIVE_VAGUE="vague";
		public static final String NEGATIVE_UNDESIRABLE ="undesirable";
		public static final String NEGATIVE_VENGEFUL="vengeful";
		public static final String NEGATIVE_VULGAR="vulgar";
		public static final String NEGATIVE_WARY="wary";
		public static final String NEGATIVE_WEAK="weak";
		public static final String NEGATIVE_WASTEFUL="wasteful";
		public static final String NEGATIVE_WEARY="weary";
		public static final String NEGATIVE_WICKED="wicked";
		public static final String NEGATIVE_WORRIED="worried";
		public static final String NEGATIVE_WORTHLESS="worthless";
		public static final String NEGATIVE_WRETCHED="wretched";
    
    
    /******************************/
    
    
    private static String _splitSpace = "\\s+";
    private static String _splitBoundary = "\\W+";
    private static String _splitComma = ",\\s*";
    private static String _splitPunct = "[.,!?:;]+\\s*";

    private static String _space = " ";
    
    public WordMap()
    {
    	
        this.stoplist = new Hashtable<String, Boolean>(); //remove the stop words
        this.negativelist = new Hashtable<String, Boolean>(); //build a map of negative words
        this.positivelist = new Hashtable<String, Boolean>(); //build a map of positive words
        
        
        this.addStandardStopWords();
        this.addNegativeStopWords();
        this.addPositiveStopWords();
        return;
    }
    
    

    /**
     *  Split words based on white space
     */
    private List<String> splitWords(String input)
    {
    	List<String> resultSet = new Vector<String>();
    	
    	String result[] = input.split(_splitSpace);
    	// remove any punctuation (other than apostrophe) from word
    	// and change to all lower case
    	for ( String word : result )
    	{
    		word = word.replaceAll("[.,!?:;]", "");
    		word = word.toLowerCase();
    		resultSet.add(word);
    	}
    	return resultSet;
    }
    
   
    public String purgeStandardStopWords(String input)
    {
    	
    	StringBuffer output = new StringBuffer();
    	
    
    	List<String> result = this.splitWords(input);
    	for ( String word : result )
    	{
    		if ( this.stoplist.containsKey(word))
    		{
    			
    		}
    		else
    		{
    			output.append(word + _space);
    		}
    	}
    	return output.toString();
    }
    
    
    public String purgeNegativeWords(String input)
    {
    	StringBuffer output = new StringBuffer();	
    	List<String> result = this.splitWords(input);
    	for ( String word : result )
    	{
    		if ( !this.negativelist.containsKey(word) )
    			output.append(word + _space);
    	}
    	return output.toString();
    }  

   
    public String findNegativeWords(String input)
    {
    	StringBuffer output = new StringBuffer();	
    	List<String> result = this.splitWords(input);
    	for ( String word : result )
    	{
    		if ( this.negativelist.containsKey(word) )
    			output.append(word + _space);
    	}
    	return output.toString();
    }  
    
   
    public String findPositiveWords(String input)
    {
    	StringBuffer output = new StringBuffer();	
    	List<String> result = this.splitWords(input);
    	for ( String word : result )
    	{
    		if ( this.positivelist.containsKey(word) )
    			output.append(word + _space);
    	}
    	return output.toString();
    }      
    
   
    public String purgePositiveWords(String input)
    {
    	StringBuffer output = new StringBuffer();	
    	List<String> result = this.splitWords(input);
    	for ( String word : result )
    	{
    		if ( !this.positivelist.containsKey(word) )
    			output.append(word + _space);
    	}
    	return output.toString();
    }    
    
    private void addNegativeStopWords()
    {
    	this.negativelist.put("faded", true);
		this.negativelist.put("evil", true);
		this.negativelist.put("evasive", true);
		this.negativelist.put("erratic", true);
		this.negativelist.put("envious", true);
		this.negativelist.put("embarrassed", true);
		this.negativelist.put("draconian", true);
		this.negativelist.put("disturbing", true);
		this.negativelist.put("domineering", true);
		this.negativelist.put("disillusioned", true);
		this.negativelist.put("depressed", true);
		this.negativelist.put("defiant", true);
		this.negativelist.put("deranged", true);
		this.negativelist.put("disagreeable", true);
		this.negativelist.put("defective", true);
		this.negativelist.put("defeated", true);
		this.negativelist.put("deceitful", true);
		this.negativelist.put("dangerous ", true);
		this.negativelist.put("cruel", true);
		this.negativelist.put("creepy", true);
		this.negativelist.put("cynical", true);
		this.negativelist.put("crazy", true);
		this.negativelist.put("cowardly", true);
		this.negativelist.put("confused", true);
		this.negativelist.put("combative", true);
		this.negativelist.put("clumsy", true);
		this.negativelist.put("careless", true);
		this.negativelist.put("callous", true);
		this.negativelist.put("boring", true);
		this.negativelist.put("angry", true);
		this.negativelist.put("annoyed", true);
		this.negativelist.put("anxious", true);
		this.negativelist.put("arrogant", true);
		this.negativelist.put("ashamed", true);
		this.negativelist.put("awful", true);
		this.negativelist.put("bad", true);
		this.negativelist.put("belligerent", true);
		this.negativelist.put("ambiguous", true);
		this.negativelist.put("bewildered", true);
		this.negativelist.put("afraid", true);
		this.negativelist.put("aloof", true);
		this.negativelist.put("abusive", true);
		this.negativelist.put("abrupt", true);
		this.negativelist.put("abrasive", true);
		this.negativelist.put("demonic", true);
		this.negativelist.put("fanatical", true);
		this.negativelist.put("panicky", true);
		this.negativelist.put("obnoxious", true);
		this.negativelist.put("malicious", true);
		this.negativelist.put("materialistic", true);
		this.negativelist.put("pathetic", true);
		this.negativelist.put("lacking", true);
		this.negativelist.put("jittery", true);
		this.negativelist.put("mysterious", true);
		this.negativelist.put("mean", true);
		this.negativelist.put("outrageous", true);
		this.negativelist.put("horrible", true);
		this.negativelist.put("homeless", true);
		this.negativelist.put("hesitant", true);
		this.negativelist.put("helpless", true);
		this.negativelist.put("grouchy", true);
		this.negativelist.put("greedy", true);
		this.negativelist.put("gruesome", true);
		this.negativelist.put("grieving", true);
		this.negativelist.put("frightened", true);
		this.negativelist.put("fretful", true);
		this.negativelist.put("frantic", true);
		this.negativelist.put("forgetful", true);
		this.negativelist.put("foolish", true);
		this.negativelist.put("flippant", true);
		this.negativelist.put("flashy", true);
		this.negativelist.put("finicky", true);
		this.negativelist.put("filthy", true);
		this.negativelist.put("fierce", true);
		this.negativelist.put("noisy", true);
		this.negativelist.put("lonely", true);
		this.negativelist.put("naive", true);
		this.negativelist.put("nasty", true);
		this.negativelist.put("nervous", true);
		this.negativelist.put("lazy", true);
		this.negativelist.put("repulsive", true);
		this.negativelist.put("grumpy", true);
		this.negativelist.put("quarrelsome", true);
		this.negativelist.put("ignorant", true);
		this.negativelist.put("furtive", true);
		this.negativelist.put("gullible", true);
		this.negativelist.put("ignorant", true);
		this.negativelist.put("hurt", true);
		this.negativelist.put("possessive", true);
		this.negativelist.put("ill", true);
		this.negativelist.put("irresolute", true);
		this.negativelist.put("jealous", true);
		this.negativelist.put("ruthless", true);
		this.negativelist.put("sad", true);
		this.negativelist.put("scary", true);
		this.negativelist.put("secretive", true);
		this.negativelist.put("selfish", true);
		this.negativelist.put("silly", true);
		this.negativelist.put("slow", true);
		this.negativelist.put("sneaky", true);
		this.negativelist.put("snobbish", true);
		this.negativelist.put("sore", true);
		this.negativelist.put("spendthrift", true);
		this.negativelist.put("squeamish", true);
		this.negativelist.put("stingy", true);
		this.negativelist.put("strange", true);
		this.negativelist.put("sulky", true);
		this.negativelist.put("tacky", true);
		this.negativelist.put("tense", true);
		this.negativelist.put("terrible", true);
		this.negativelist.put("testy", true);
		this.negativelist.put("thick-skinned", true);
		this.negativelist.put("thoughtless", true);
		this.negativelist.put("threatening", true);
		this.negativelist.put("tight", true);
		this.negativelist.put("timid", true);
		this.negativelist.put("tired", true);
		this.negativelist.put("tiresome", true);
		this.negativelist.put("troubled", true);
		this.negativelist.put("typical", true);
		this.negativelist.put("uptight", true);
		this.negativelist.put("upset", true);
		this.negativelist.put("unsure", true);
		this.negativelist.put("unsuitable", true);
		this.negativelist.put("vague", true);
		this.negativelist.put("undesirable", true);
		this.negativelist.put("vengeful", true);
		this.negativelist.put("venomous", true);
		this.negativelist.put("vulgar", true);
		this.negativelist.put("volatile", true);
		this.negativelist.put("wary", true);
		this.negativelist.put("weak", true);
		this.negativelist.put("wasteful", true);
		this.negativelist.put("weary", true);
		this.negativelist.put("wicked", true);
		this.negativelist.put("worried", true);
		this.negativelist.put("worthless", true);
		this.negativelist.put("wretched", true);    
    }

    private void addPositiveStopWords()
    {
    	this.positivelist.put("happy", true);
    	this.positivelist.put("grateful", true);
    	this.positivelist.put("determined", true);
    	this.positivelist.put("professional", true);
    	this.positivelist.put("swell", true);
    	this.positivelist.put("helpful", true);
    	this.positivelist.put("sincere", true);
    	this.positivelist.put("authentic", true);
    	this.positivelist.put("content", true);
    	this.positivelist.put("focused", true);
    	this.positivelist.put("extraordinary", true);
    	this.positivelist.put("delightful", true);
    	this.positivelist.put("imaginative", true);
    	this.positivelist.put("reverent", true);
    	this.positivelist.put("successful", true);
    	this.positivelist.put("heroic", true);
    	this.positivelist.put("cheerful", true);
    	this.positivelist.put("inventive", true);
    	this.positivelist.put("unique", true);
    	this.positivelist.put("tidy", true);
    	this.positivelist.put("blissful", true);
    	this.positivelist.put("tough", true);
    	this.positivelist.put("glad", true);
    	this.positivelist.put("reposed", true);
    	this.positivelist.put("desirable", true);
    	this.positivelist.put("valiant", true);
    	this.positivelist.put("fair-minded", true);
    	this.positivelist.put("open-minded", true);
    	this.positivelist.put("modest", true);
    	this.positivelist.put("ingenious", true);
    	this.positivelist.put("solid", true);
    	this.positivelist.put("courageous", true);
    	this.positivelist.put("profound", true);
    	this.positivelist.put("adaptable", true);
    	this.positivelist.put("worthy", true);
    	this.positivelist.put("colorful", true);
    	this.positivelist.put("joyful", true);
    	this.positivelist.put("laudable", true);
    	this.positivelist.put("cute", true);
    	this.positivelist.put("dependable", true);
    	this.positivelist.put("remarkable", true);
    	this.positivelist.put("confident", true);
    	this.positivelist.put("forbearing", true);
    	this.positivelist.put("funny", true);
    	this.positivelist.put("ready", true);
    	this.positivelist.put("lenient", true);
    	this.positivelist.put("magnetic", true);
    	this.positivelist.put("enlightened", true);
    	this.positivelist.put("authoritative", true);
    	this.positivelist.put("enterprising", true);
    	this.positivelist.put("authoritative", true);
    	this.positivelist.put("enterprising", true);
    	this.positivelist.put("righteous", true);
    	this.positivelist.put("exact", true);
    	this.positivelist.put("cognizant", true);
    	this.positivelist.put("ecstatic", true);
    	this.positivelist.put("lovely", true);
    	this.positivelist.put("entertaining", true);
    	this.positivelist.put("inspired", true);
    	this.positivelist.put("thorough", true);
    	this.positivelist.put("decent", true);
    	this.positivelist.put("helpful", true);
    	this.positivelist.put("pragmatic", true);
    	this.positivelist.put("witty", true);
    	this.positivelist.put("convincing", true);
    	this.positivelist.put("beautiful", true);
    	this.positivelist.put("assured", true);
    	this.positivelist.put("competent", true);
    	this.positivelist.put("progressive", true);
    	this.positivelist.put("accessible", true);
    	this.positivelist.put("commendable", true);
    	this.positivelist.put("sensual", true);
    	this.positivelist.put("sublime", true);
    	this.positivelist.put("sympathetic", true);
    	this.positivelist.put("compatible", true);
    	this.positivelist.put("hospitable", true);
    	this.positivelist.put("exultant", true);
    	this.positivelist.put("faithful", true);
    	this.positivelist.put("adroit", true);
    	this.positivelist.put("earnest", true);
    	this.positivelist.put("serene", true);
    	this.positivelist.put("knowledgeable", true);
    	this.positivelist.put("lucky", true);
    	this.positivelist.put("gentle", true);
    	this.positivelist.put("believable", true);
    	this.positivelist.put("merciful", true);
    	this.positivelist.put("civil", true);
    	this.positivelist.put("engaging", true);
    	this.positivelist.put("humorous", true);
    	this.positivelist.put("efficient", true);
    	this.positivelist.put("influential", true);
    	this.positivelist.put("discrete", true);
    	this.positivelist.put("warm", true);
    	this.positivelist.put("pleasant", true);
    	this.positivelist.put("devoted", true);
    	this.positivelist.put("original", true);
    	this.positivelist.put("superb", true);
    	this.positivelist.put("intelligent", true);
    	this.positivelist.put("playful", true);
    	this.positivelist.put("impressive", true);
    	this.positivelist.put("elated", true);
    	this.positivelist.put("punctual", true);
    	this.positivelist.put("credible", true);
    	this.positivelist.put("reflective", true);
    	this.positivelist.put("companionable", true);
    	this.positivelist.put("alluring", true);
    	this.positivelist.put("wonderful", true);
    	this.positivelist.put("vigorous", true);
    	this.positivelist.put("proper", true);
    	this.positivelist.put("mild", true);
    	this.positivelist.put("chatty", true);
    	this.positivelist.put("bright", true);
    	this.positivelist.put("diplomatic", true);
    	this.positivelist.put("immaculate", true);
    	this.positivelist.put("defined", true);
    	this.positivelist.put("whimsical", true);
    	this.positivelist.put("jolly", true);
    	this.positivelist.put("fantastic", true);
    	this.positivelist.put("tender", true);	
    	this.positivelist.put("accommodating", true);
    	this.positivelist.put("rich", true);
    	this.positivelist.put("bold", true);
    	this.positivelist.put("fun", true);
    	this.positivelist.put("nice", true);
    	this.positivelist.put("even-tempered", true);
    	this.positivelist.put("conciliatory", true);
    	this.positivelist.put("lucid", true);
    	this.positivelist.put("benevolent", true);
    	this.positivelist.put("harmonious", true);
    	this.positivelist.put("approachable", true);
    	this.positivelist.put("right", true);
    	this.positivelist.put("learned", true);
    	this.positivelist.put("meritorious", true);
    	this.positivelist.put("genteel", true);
    	this.positivelist.put("creative", true);
    	this.positivelist.put("just", true);
    	this.positivelist.put("healthy", true);
    	this.positivelist.put("agile", true);
    	this.positivelist.put("restrained", true);
    	this.positivelist.put("law-abiding", true);
    	this.positivelist.put("cozy", true);
    	this.positivelist.put("satisfied", true);
    	this.positivelist.put("precious", true);
    	this.positivelist.put("responsive", true);
    	this.positivelist.put("gregarious", true);
    	this.positivelist.put("diligent", true);
    	this.positivelist.put("noble", true);
    	this.positivelist.put("athletic", true);
    	this.positivelist.put("enchanted", true);
    	this.positivelist.put("upright", true);
    	this.positivelist.put("innocent", true);
    	this.positivelist.put("hardy", true);
    	this.positivelist.put("perfect", true);
    	this.positivelist.put("brave", true);
    	this.positivelist.put("industrious", true);
    	this.positivelist.put("practical", true);
    	this.positivelist.put("gorgeous", true);
    	this.positivelist.put("truthful", true);
    	this.positivelist.put("grounded", true);
    	this.positivelist.put("liberal", true);
    	this.positivelist.put("shrewd", true);
    	this.positivelist.put("receptive", true);
    	this.positivelist.put("charming", true);
    	this.positivelist.put("alive", true);
    	this.positivelist.put("stable", true);
    	this.positivelist.put("loyal", true);
    	this.positivelist.put("casual", true);
    	this.positivelist.put("comfortable", true);
    	this.positivelist.put("sensible", true);
    	this.positivelist.put("eloquent", true);
    	this.positivelist.put("relaxed", true);
    	this.positivelist.put("merry", true);
    	this.positivelist.put("keen", true);
    	this.positivelist.put("natural", true);
    	this.positivelist.put("constant", true);
    	this.positivelist.put("impartial", true);
    	this.positivelist.put("brilliant", true);
    	this.positivelist.put("fascinating", true);
    	this.positivelist.put("spontaneous", true);
    	this.positivelist.put("appreciative", true);
    	this.positivelist.put("soulful", true);
    	this.positivelist.put("cordial", true);
    	this.positivelist.put("sparkling", true);
    	this.positivelist.put("gleeful", true);
    	this.positivelist.put("radiant", true);
    	this.positivelist.put("resolute", true);
    	this.positivelist.put("important", true);
    	this.positivelist.put("sagacious", true);
    	this.positivelist.put("established", true);
    	this.positivelist.put("privileged", true);
    	this.positivelist.put("beneficent", true);
    	this.positivelist.put("philosophical", true);
    	this.positivelist.put("rejoicing", true);
    	this.positivelist.put("astute", true);
    	this.positivelist.put("seemly", true);
    	this.positivelist.put("accomplished", true);
    	this.positivelist.put("autonomous", true);
    	this.positivelist.put("scholarly", true);
    	this.positivelist.put("complex", true);
    	this.positivelist.put("spry", true);
    	this.positivelist.put("smooth", true);
    	this.positivelist.put("blissful", true);
    	this.positivelist.put("genuine", true);
    	this.positivelist.put("artistic", true);
    	this.positivelist.put("consummate", true);
    	this.positivelist.put("compassionate", true);
    	this.positivelist.put("independent", true);
    	this.positivelist.put("openhanded", true);
    	this.positivelist.put("godly", true);
    	this.positivelist.put("congenial", true);
    	this.positivelist.put("blessed", true);
    	this.positivelist.put("admirable", true);
    	this.positivelist.put("real", true);
    	this.positivelist.put("polished", true);
    	this.positivelist.put("deserving", true);
    	this.positivelist.put("daring", true);
    	this.positivelist.put("free", true);
    	this.positivelist.put("tolerant", true);
    	this.positivelist.put("great", true);
    	this.positivelist.put("fertile", true);
    	this.positivelist.put("masterly", true);
    	this.positivelist.put("elegant", true);
    	this.positivelist.put("fruitful", true);
    	this.positivelist.put("understanding", true);
    	this.positivelist.put("mindful", true);
    	this.positivelist.put("forgiving", true);
    	this.positivelist.put("affectionate", true);
    	this.positivelist.put("jubilant", true);
    	this.positivelist.put("cerebral", true);
    	this.positivelist.put("thoughtful", true);
    	this.positivelist.put("provident", true);
    	this.positivelist.put("attentive", true);
    	this.positivelist.put("virtuous", true);
    	this.positivelist.put("tranquil", true);
    	this.positivelist.put("logical", true);
    	this.positivelist.put("fine", true);
    	this.positivelist.put("caring", true);
    	this.positivelist.put("disarming", true);
    	this.positivelist.put("winsome", true);
    	this.positivelist.put("heedful", true);
    	this.positivelist.put("intuitive", true);
    	this.positivelist.put("chic", true);
    	this.positivelist.put("sleek", true);
    	this.positivelist.put("excellent", true);
    	this.positivelist.put("affable", true);
    	this.positivelist.put("hopeful", true);
    	this.positivelist.put("stylish", true);
    	this.positivelist.put("subtle", true);
    	this.positivelist.put("peaceful", true);
    	this.positivelist.put("personable", true);
    	this.positivelist.put("brainy", true);
    	this.positivelist.put("decisive", true);
    	this.positivelist.put("confident", true);
    	this.positivelist.put("good", true);
    	this.positivelist.put("calm", true);
    	this.positivelist.put("amazing", true);
    	this.positivelist.put("persuasive", true);
    	this.positivelist.put("dedicated", true);
    	this.positivelist.put("consistent", true);
    	this.positivelist.put("robust", true);
    	this.positivelist.put("philanthropic", true);
    	this.positivelist.put("wise", true);
    	this.positivelist.put("direct", true);
    	this.positivelist.put("affirmative", true);
    	this.positivelist.put("goodhearted", true);
    	this.positivelist.put("altruistic", true);
    	this.positivelist.put("gracious", true);
    	this.positivelist.put("fabulous", true);
    	this.positivelist.put("convulsive", true);
    	this.positivelist.put("powerful", true);
    	this.positivelist.put("special", true);
    	this.positivelist.put("discriminating", true);
    	this.positivelist.put("responsible", true);
    	this.positivelist.put("distinctive", true);
    	this.positivelist.put("active", true);
    	this.positivelist.put("sprite", true);
    	this.positivelist.put("strong", true);
    	this.positivelist.put("captivating", true);
    	this.positivelist.put("moderate", true);
    	this.positivelist.put("accountable", true);
    	this.positivelist.put("passionate", true);
    	this.positivelist.put("enthusiastic", true);
    	this.positivelist.put("purposeful", true);
    	this.positivelist.put("well-rounded", true);
    	this.positivelist.put("benign", true);
    	this.positivelist.put("concise", true);
    	this.positivelist.put("balanced", true);
    	this.positivelist.put("speedy", true);
    	this.positivelist.put("moral", true);
    	this.positivelist.put("thrifty", true);
    	this.positivelist.put("amiable", true);
    	this.positivelist.put("versatile", true);
    	this.positivelist.put("encouraging", true);
    	this.positivelist.put("dutiful", true);
    	this.positivelist.put("heavenly", true);
    	this.positivelist.put("agreeable", true);
    	this.positivelist.put("dignified", true);
    	this.positivelist.put("tender", true);
    	this.positivelist.put("vivacious", true);
    	this.positivelist.put("prudent", true);
    	this.positivelist.put("lively", true);
    	this.positivelist.put("ethical", true);
    	this.positivelist.put("visionary", true);
    	this.positivelist.put("ambitious", true);
    	this.positivelist.put("attractive", true);
    	this.positivelist.put("poetic", true);
    	this.positivelist.put("sentimental", true);
    	this.positivelist.put("appropriate", true);
    	this.positivelist.put("adorable", true);
    	this.positivelist.put("likeable", true);
    	this.positivelist.put("romantic", true);
    	this.positivelist.put("valiant", true);
    	this.positivelist.put("gallant", true);
    	this.positivelist.put("refined", true);
    	this.positivelist.put("considerate", true);
    	this.positivelist.put("systematic", true);
    	this.positivelist.put("airy", true);
    	this.positivelist.put("positive", true);
    	this.positivelist.put("thankful", true);
    	this.positivelist.put("nourishing", true);
    	this.positivelist.put("handy", true);
    	this.positivelist.put("spirited", true);
    	this.positivelist.put("steady", true);
    	this.positivelist.put("precious", true);
    	this.positivelist.put("appreciative", true);
    	this.positivelist.put("respectful", true);
    	this.positivelist.put("hilarious", true);
    	this.positivelist.put("priceless", true);
    	this.positivelist.put("reasonable", true);
    	this.positivelist.put("fashionable", true);
    	this.positivelist.put("forthright", true);
    	this.positivelist.put("comely", true);
    	this.positivelist.put("spiritual", true);
    	this.positivelist.put("light", true);
    	this.positivelist.put("lightweight", true);
    	this.positivelist.put("mature", true);
    	this.positivelist.put("generous", true);
    	this.positivelist.put("discerning", true);
    	this.positivelist.put("candid", true);
    	this.positivelist.put("energetic", true);
    	this.positivelist.put("worldly", true);
    	this.positivelist.put("sophisticated", true);
    	this.positivelist.put("splendid", true);
    	this.positivelist.put("prolific", true);
    	this.positivelist.put("suave", true);
    	this.positivelist.put("amicable", true);
    	this.positivelist.put("sunny", true);
    	this.positivelist.put("rosy", true);
    	this.positivelist.put("self-reliant", true);
    	this.positivelist.put("modern", true);
    	this.positivelist.put("good looking", true);
    	this.positivelist.put("prompt", true);
    	this.positivelist.put("dependable", true);
    	this.positivelist.put("clearheaded", true);
    	this.positivelist.put("sincere", true);
    	this.positivelist.put("awesome", true);
    	this.positivelist.put("willing", true);
    	this.positivelist.put("good-natured", true);
    	this.positivelist.put("productive", true);
    	this.positivelist.put("charitable", true);
    	this.positivelist.put("sharp", true);
    	this.positivelist.put("impressive", true);
    	this.positivelist.put("sweet", true);
    	this.positivelist.put("democratic", true);
    	this.positivelist.put("terrific", true);
    	this.positivelist.put("reliable", true);
    	this.positivelist.put("flexible", true);
    	this.positivelist.put("deliberate", true);
    	this.positivelist.put("genial", true);
    	this.positivelist.put("good mannered", true);
    	this.positivelist.put("easy-going", true);    
    }

   
    private void addStandardStopWords()
    {
    	this.stoplist.put("about", true);
    	this.stoplist.put("above", true);
    	this.stoplist.put("across", true);
    	this.stoplist.put("actually", true);
    	this.stoplist.put("add", true);
    	this.stoplist.put("after", true);
    	this.stoplist.put("against", true);
    	this.stoplist.put("again", true);
    	this.stoplist.put("allow", true);
    	this.stoplist.put("all", true);
    	this.stoplist.put("also", true);
    	this.stoplist.put("always", true);
    	this.stoplist.put("among", true);
    	this.stoplist.put("am", true);
    	this.stoplist.put("and", true);
    	this.stoplist.put("another", true);
    	this.stoplist.put("an", true);
    	this.stoplist.put("any", true);
    	this.stoplist.put("april", true);
    	this.stoplist.put("aren't", true);
    	this.stoplist.put("are", true);
    	this.stoplist.put("ask", true);
    	this.stoplist.put("as", true);
    	this.stoplist.put("a", true);
    	this.stoplist.put("at", true);
    	this.stoplist.put("august", true);
    	this.stoplist.put("back", true);
    	this.stoplist.put("because", true);
    	this.stoplist.put("been", true);
    	this.stoplist.put("before", true);
    	this.stoplist.put("being", true);
    	this.stoplist.put("below", true);
    	this.stoplist.put("be", true);
    	this.stoplist.put("between", true);
    	this.stoplist.put("big", true);
    	this.stoplist.put("both", true);
    	this.stoplist.put("b", true);
    	this.stoplist.put("but", true);
    	this.stoplist.put("by", true);
    	this.stoplist.put("call", true);
    	this.stoplist.put("came", true);
    	this.stoplist.put("cannot", true);
    	this.stoplist.put("can", true);
    	this.stoplist.put("can't", true);
    	this.stoplist.put("cause", true);
    	this.stoplist.put("close", true);
    	this.stoplist.put("come", true);
    	this.stoplist.put("couldn't", true);
    	this.stoplist.put("could", true);
    	this.stoplist.put("c", true);
    	this.stoplist.put("daren't", true);
    	this.stoplist.put("day", true);
    	this.stoplist.put("december", true);
    	this.stoplist.put("didn't", true);
    	this.stoplist.put("did", true);
    	this.stoplist.put("doesn't", true);
    	this.stoplist.put("does", true);
    	this.stoplist.put("doing", true);
    	this.stoplist.put("don't", true);
    	this.stoplist.put("do", true);
    	this.stoplist.put("down", true);
    	this.stoplist.put("d", true);
    	this.stoplist.put("during", true);
    	this.stoplist.put("each", true);
    	this.stoplist.put("end", true);
    	this.stoplist.put("especially", true);
    	this.stoplist.put("e", true);
    	this.stoplist.put("even", true);
    	this.stoplist.put("ever", true);
    	this.stoplist.put("every", true);
    	this.stoplist.put("examining", true);
    	this.stoplist.put("february", true);
    	this.stoplist.put("few", true);
    	this.stoplist.put("find", true);
    	this.stoplist.put("first", true);
    	this.stoplist.put("five", true);
    	this.stoplist.put("for", true);
    	this.stoplist.put("four", true);
    	this.stoplist.put("friday", true);
    	this.stoplist.put("from", true);
    	this.stoplist.put("f", true);
    	this.stoplist.put("further", true);
    	this.stoplist.put("get", true);
    	this.stoplist.put("goes", true);
    	this.stoplist.put("go", true);
    	this.stoplist.put("got", true);
    	this.stoplist.put("g", true);
    	this.stoplist.put("hadn't", true);
    	this.stoplist.put("had", true);
    	this.stoplist.put("hand", true);
    	this.stoplist.put("hasn't", true);
    	this.stoplist.put("has", true);
    	this.stoplist.put("haven't", true);
    	this.stoplist.put("have", true);
    	this.stoplist.put("having", true);
    	this.stoplist.put("he'd", true);
    	this.stoplist.put("he'll", true);
    	this.stoplist.put("here's", true);
    	this.stoplist.put("here", true);
    	this.stoplist.put("herself", true);
    	this.stoplist.put("hers", true);
    	this.stoplist.put("her", true);
    	this.stoplist.put("he's", true);
    	this.stoplist.put("he", true);
    	this.stoplist.put("high", true);
    	this.stoplist.put("himself", true);
    	this.stoplist.put("him", true);
    	this.stoplist.put("his", true);
    	this.stoplist.put("hot", true);
    	this.stoplist.put("however", true);
    	this.stoplist.put("how's", true);
    	this.stoplist.put("how", true);
    	this.stoplist.put("h", true);
    	this.stoplist.put("i'd", true);
    	this.stoplist.put("if", true);
    	this.stoplist.put("i'll", true);
    	this.stoplist.put("i'm", true);
    	this.stoplist.put("inside", true);
    	this.stoplist.put("into", true);
    	this.stoplist.put("in", true);
    	this.stoplist.put("isn't", true);
    	this.stoplist.put("is", true);
    	this.stoplist.put("it'd", true);
    	this.stoplist.put("it'll", true);
    	this.stoplist.put("i", true);
    	this.stoplist.put("I", true);
    	this.stoplist.put("itself", true);
    	this.stoplist.put("it's", true);
    	this.stoplist.put("its", true);
    	this.stoplist.put("it", true);
    	this.stoplist.put("i've", true);
    	this.stoplist.put("january", true);
    	this.stoplist.put("j", true);
    	this.stoplist.put("july", true);
    	this.stoplist.put("june", true);
    	this.stoplist.put("just", true);
    	this.stoplist.put("kind", true);
    	this.stoplist.put("know", true);
    	this.stoplist.put("k", true);
    	this.stoplist.put("large", true);
    	this.stoplist.put("last", true);
    	this.stoplist.put("late", true);
    	this.stoplist.put("least", true);
    	this.stoplist.put("left", true);
    	this.stoplist.put("less", true);
    	this.stoplist.put("let's", true);
    	this.stoplist.put("let", true);
    	this.stoplist.put("like", true);
    	this.stoplist.put("little", true);
    	this.stoplist.put("ll", true);
    	this.stoplist.put("long", true);
    	this.stoplist.put("look", true);
    	this.stoplist.put("low", true);
    	this.stoplist.put("l", true);
    	this.stoplist.put("made", true);
    	this.stoplist.put("makes", true);
    	this.stoplist.put("make", true);
    	this.stoplist.put("many", true);
    	this.stoplist.put("march", true);
    	this.stoplist.put("may", true);
    	this.stoplist.put("mean", true);
    	this.stoplist.put("men", true);
    	this.stoplist.put("me", true);
    	this.stoplist.put("mightn't", true);
    	this.stoplist.put("might", true);
    	this.stoplist.put("monday", true);
    	this.stoplist.put("more", true);
    	this.stoplist.put("most", true);
    	this.stoplist.put("move", true);
    	this.stoplist.put("m", true);
    	this.stoplist.put("much", true);
    	this.stoplist.put("mustn't", true);
    	this.stoplist.put("must", true);
    	this.stoplist.put("myself", true);
    	this.stoplist.put("my", true);
    	this.stoplist.put("near", true);
    	this.stoplist.put("needn't", true);
    	this.stoplist.put("need", true);
    	this.stoplist.put("never", true);
    	this.stoplist.put("new", true);
    	this.stoplist.put("next", true);
    	this.stoplist.put("nor", true);
    	this.stoplist.put("no", true);
    	this.stoplist.put("not", true);
    	this.stoplist.put("november", true);
    	this.stoplist.put("now", true);
    	this.stoplist.put("n", true);
    	this.stoplist.put("october", true);
    	this.stoplist.put("off", true);
    	this.stoplist.put("often", true);
    	this.stoplist.put("of", true);
    	this.stoplist.put("old", true);
    	this.stoplist.put("once", true);
    	this.stoplist.put("one", true);
    	this.stoplist.put("only", true);
    	this.stoplist.put("on", true);
    	this.stoplist.put("or", true);
    	this.stoplist.put("other", true);
    	this.stoplist.put("o", true);
    	this.stoplist.put("oughtn't", true);
    	this.stoplist.put("ought", true);
    	this.stoplist.put("ourselves", true);
    	this.stoplist.put("ours", true);
    	this.stoplist.put("our", true);
    	this.stoplist.put("out", true);
    	this.stoplist.put("over", true);
    	this.stoplist.put("own", true);
    	this.stoplist.put("part", true);
    	this.stoplist.put("place", true);
    	this.stoplist.put("p", true);
    	this.stoplist.put("put", true);
    	this.stoplist.put("q", true);
    	this.stoplist.put("rd", true);
    	this.stoplist.put("re", true);
    	this.stoplist.put("right", true);
    	this.stoplist.put("r", true);
    	this.stoplist.put("run", true);
    	this.stoplist.put("said", true);
    	this.stoplist.put("same", true);
    	this.stoplist.put("saturday", true);
    	this.stoplist.put("saw", true);
    	this.stoplist.put("says", true);
    	this.stoplist.put("say", true);
    	this.stoplist.put("second", true);
    	this.stoplist.put("seem", true);
    	this.stoplist.put("seen", true);
    	this.stoplist.put("see", true);
    	this.stoplist.put("september", true);
    	this.stoplist.put("set", true);
    	this.stoplist.put("shall", true);
    	this.stoplist.put("shan't", true);
    	this.stoplist.put("she'd", true);
    	this.stoplist.put("she'll", true);
    	this.stoplist.put("she's", true);
    	this.stoplist.put("she", true);
    	this.stoplist.put("shouldn't", true);
    	this.stoplist.put("should", true);
    	this.stoplist.put("should't", true);
    	this.stoplist.put("show", true);
    	this.stoplist.put("side", true);
    	this.stoplist.put("since", true);
    	this.stoplist.put("small", true);
    	this.stoplist.put("some", true);
    	this.stoplist.put("so", true);
    	this.stoplist.put("still", true);
    	this.stoplist.put("s", true);
    	this.stoplist.put("st", true);
    	this.stoplist.put("such", true);
    	this.stoplist.put("take", true);
    	this.stoplist.put("tell", true);
    	this.stoplist.put("tenth", true);
    	this.stoplist.put("than", true);
    	this.stoplist.put("that's", true);
    	this.stoplist.put("that", true);
    	this.stoplist.put("theirs", true);
    	this.stoplist.put("their", true);
    	this.stoplist.put("themselves", true);
    	this.stoplist.put("them", true);
    	this.stoplist.put("then", true);
    	this.stoplist.put("there's", true);
    	this.stoplist.put("there", true);
    	this.stoplist.put("these", true);
    	this.stoplist.put("the", true);
    	this.stoplist.put("they'd", true);
    	this.stoplist.put("they'll", true);
    	this.stoplist.put("they're", true);
    	this.stoplist.put("they", true);
    	this.stoplist.put("they've", true);
    	this.stoplist.put("thing", true);
    	this.stoplist.put("this", true);
    	this.stoplist.put("those", true);
    	this.stoplist.put("though", true);
    	this.stoplist.put("three", true);
    	this.stoplist.put("through", true);
    	this.stoplist.put("th", true);
    	this.stoplist.put("thursday", true);
    	this.stoplist.put("thus", true);
    	this.stoplist.put("time", true);
    	this.stoplist.put("too", true);
    	this.stoplist.put("to", true);
    	this.stoplist.put("trying", true);
    	this.stoplist.put("try", true);
    	this.stoplist.put("t", true);
    	this.stoplist.put("tuesday", true);
    	this.stoplist.put("two", true);
    	this.stoplist.put("under", true);
    	this.stoplist.put("until", true);
    	this.stoplist.put("upon", true);
    	this.stoplist.put("up", true);
    	this.stoplist.put("use", true);
    	this.stoplist.put("using", true);
    	this.stoplist.put("us", true);
    	this.stoplist.put("u", true);
    	this.stoplist.put("very", true);
    	this.stoplist.put("ve", true);
    	this.stoplist.put("v", true);
    	this.stoplist.put("want", true);
    	this.stoplist.put("wasn't", true);
    	this.stoplist.put("was", true);
    	this.stoplist.put("way", true);
    	this.stoplist.put("wednesday", true);
    	this.stoplist.put("we'd", true);
    	this.stoplist.put("we'll", true);
    	this.stoplist.put("well", true);
    	this.stoplist.put("went", true);
    	this.stoplist.put("weren't", true);
    	this.stoplist.put("we're", true);
    	this.stoplist.put("were", true);
    	this.stoplist.put("we", true);
    	this.stoplist.put("we've", true);
    	this.stoplist.put("what's", true);
    	this.stoplist.put("what", true);
    	this.stoplist.put("when's", true);
    	this.stoplist.put("when", true);
    	this.stoplist.put("where's", true);
    	this.stoplist.put("where", true);
    	this.stoplist.put("whether", true);
    	this.stoplist.put("which", true);
    	this.stoplist.put("while", true);
    	this.stoplist.put("who'll", true);
    	this.stoplist.put("whom", true);
    	this.stoplist.put("who's", true);
    	this.stoplist.put("who", true);
    	this.stoplist.put("who've", true);
    	this.stoplist.put("why's", true);
    	this.stoplist.put("why", true);
    	this.stoplist.put("will", true);
    	this.stoplist.put("within", true);
    	this.stoplist.put("without", true);
    	this.stoplist.put("with", true);
    	this.stoplist.put("won't", true);
    	this.stoplist.put("word", true);
    	this.stoplist.put("wouldn't", true);
    	this.stoplist.put("would", true);
    	this.stoplist.put("write", true);
    	this.stoplist.put("w", true);
    	this.stoplist.put("x", true);
    	this.stoplist.put("yes", true);
    	this.stoplist.put("yet", true);
    	this.stoplist.put("you'd", true);
    	this.stoplist.put("you'll", true);
    	this.stoplist.put("you're", true);
    	this.stoplist.put("yourself", true);
    	this.stoplist.put("yourselves", true);
    	this.stoplist.put("yours", true);
    	this.stoplist.put("your", true);
    	this.stoplist.put("you", true);
    	this.stoplist.put("you've", true);
    	this.stoplist.put("y", true);
    	this.stoplist.put("z", true);    	
        
        // All amazon reviews have 'star' ratings
        this.stoplist.put("star", true);
        this.stoplist.put("stars", true);
        this.stoplist.put("review", true);
        this.stoplist.put("reviews", true);
        this.stoplist.put("product", true);
        this.stoplist.put("comment", true);
        this.stoplist.put("comments", true);
        this.stoplist.put("permalink", true);
        
        // symbols
        this.stoplist.put("|", true);
        this.stoplist.put("+", true);
    	this.stoplist.put("--", true);
        this.stoplist.put("-", true);
        this.stoplist.put("=", true);
        this.stoplist.put("!", true);
        this.stoplist.put("@", true);
        this.stoplist.put("#", true);
        this.stoplist.put("$", true);
        this.stoplist.put("%", true);
        this.stoplist.put("^", true);
        this.stoplist.put("&", true);
        this.stoplist.put("*", true);
        this.stoplist.put("[", true);
        this.stoplist.put("]", true);
        this.stoplist.put("(", true);
        this.stoplist.put(")", true);
        this.stoplist.put(";", true);
        this.stoplist.put(":", true);
    	this.stoplist.put("''", true);
    	
    	// Months
    	this.stoplist.put("january", true);
    	this.stoplist.put("february", true);
    	this.stoplist.put("march", true);
    	this.stoplist.put("april", true);
    	this.stoplist.put("may", true);
    	this.stoplist.put("june", true);
    	this.stoplist.put("july", true);
    	this.stoplist.put("august", true);
    	this.stoplist.put("september", true);
    	this.stoplist.put("october", true);
    	this.stoplist.put("november", true);
    	this.stoplist.put("december", true);
    	
    	this.stoplist.put("jan", true);
    	this.stoplist.put("feb", true);
    	this.stoplist.put("mar", true);
    	this.stoplist.put("apr", true);
    	this.stoplist.put("jun", true);
    	this.stoplist.put("jul", true);
    	this.stoplist.put("aug", true);
    	this.stoplist.put("sep", true);
    	this.stoplist.put("oct", true);
    	this.stoplist.put("nov", true);
    	this.stoplist.put("dec", true);

    	// years
    	this.stoplist.put("2000", true);
    	this.stoplist.put("2001", true);
    	this.stoplist.put("2002", true);
    	this.stoplist.put("2003", true);
    	this.stoplist.put("2004", true);
    	this.stoplist.put("2005", true);
    	this.stoplist.put("2006", true);
    	this.stoplist.put("2007", true);
    	this.stoplist.put("2008", true);
    	this.stoplist.put("2009", true);
    	this.stoplist.put("2010", true);
    	this.stoplist.put("2011", true);
    	this.stoplist.put("2012", true);

    	// numbers 1-20, remove
    	this.stoplist.put("1", true);
    	this.stoplist.put("2", true);
    	this.stoplist.put("3", true);
    	this.stoplist.put("4", true);
    	this.stoplist.put("5", true);
    	this.stoplist.put("6", true);
    	this.stoplist.put("7", true);
    	this.stoplist.put("8", true);
    	this.stoplist.put("9", true);
    	this.stoplist.put("10", true);
    	this.stoplist.put("11", true);
    	this.stoplist.put("12", true);
    	this.stoplist.put("13", true);
    	this.stoplist.put("14", true);
    	this.stoplist.put("15", true);
    	this.stoplist.put("16", true);
    	this.stoplist.put("17", true);
    	this.stoplist.put("18", true);
    	this.stoplist.put("19", true);
    	this.stoplist.put("20", true);
    	
        return;
    }

}
